language: ruby
rvm:
  - 2.5.3
script:
  - bundle exec jekyll build -d ./_site/item-issues/
  - bundle exec htmlproofer ./_site --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache: bundler # caching bundler gem packages will speed up build

notifications:
  email: false
