title: Neopets Item Issues Masterlist
description: >-
  This is a masterlist of known item issues maintained by
  <a href="http://www.neopets.com/userlookup.phtml?user=minnesotan">minnesotan</a>.
repository: williamneo/item-issues
baseurl: /item-issues

# Build settings
timezone: America/Los_Angeles
markdown: kramdown
sass:
  style: compressed
theme: jekyll-theme-modernist
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jemoji

# Content settings
collections:
  - fixed
defaults:
  -
    scope:
      path: _posts
    values:
      category: issue

permalink: /:categories/:title/
